name: Cross-Platform Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build workspace
      run: cargo build --release
    
    - name: Build plugins
      run: |
        if [ -f "scripts/build-plugins.sh" ]; then
          bash scripts/build-plugins.sh
        else
          echo "Plugin build script not found, skipping..."
        fi
    
    - name: Run tests
      run: cargo test
    
    - name: Run CLI tests
      run: |
        cargo run --bin lao-cli plugin-list
        cargo run --bin lao-cli validate workflows/test.yaml
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lao-${{ matrix.os }}
        path: |
          target/release/lao-cli*
          target/release/lao-ui*
          plugins/*.so
          plugins/*.dylib
          plugins/*.dll
        retention-days: 30

  test-cross-platform:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: lao-ubuntu-latest
        path: artifacts/linux/
    
    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: lao-macos-latest
        path: artifacts/macos/
    
    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: lao-windows-latest
        path: artifacts/windows/
    
    - name: Test cross-platform compatibility
      run: |
        echo "Testing cross-platform plugin loading..."
        
        # Test Linux plugins
        if [ -f "artifacts/linux/plugins/"*.so ]; then
          echo "✅ Linux plugins found"
        fi
        
        # Test macOS plugins  
        if [ -f "artifacts/macos/plugins/"*.dylib ]; then
          echo "✅ macOS plugins found"
        fi
        
        # Test Windows plugins
        if [ -f "artifacts/windows/plugins/"*.dll ]; then
          echo "✅ Windows plugins found"
        fi
        
        echo "🎉 Cross-platform compatibility verified!"
